<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_55555a1530f8c',
	'title' => 'Recipe details',
	'fields' => array (
		array (
			'key' => 'field_55555a2369fe5',
			'label' => 'Servings',
			'name' => 'servings',
			'type' => 'number',
			'instructions' => 'How many servings? (default: 2)',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'default_value' => 2,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'servings',
			'min' => 1,
			'max' => '',
			'step' => 1,
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55555a6769fe6',
			'label' => 'Calories',
			'name' => 'calories',
			'type' => 'number',
			'instructions' => 'Nutritional value',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'Kcal',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5555621a6cbbf',
			'label' => 'Preparation time',
			'name' => 'prep_time',
			'type' => 'number',
			'instructions' => 'Preparation time',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'minutes',
			'min' => '',
			'max' => '',
			'step' => 1,
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5557ddda4a367',
			'label' => 'Cook Time',
			'name' => 'cook_time',
			'type' => 'number',
			'instructions' => 'Cooking time',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'minutes',
			'min' => '',
			'max' => '',
			'step' => 1,
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'recipe',
			),
		),
	),
	'menu_order' => 10,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_55555319558f3',
	'title' => 'Recipe Ingredients',
	'fields' => array (
		array (
			'key' => 'field_555554369c304',
			'label' => 'Ingredients',
			'name' => 'ingredients',
			'type' => 'repeater',
			'instructions' => 'Add the ingredients the recipe requires along with their quantities',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 100,
				'class' => '',
				'id' => '',
			),
			'min' => 1,
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Ingredient',
			'sub_fields' => array (
				array (
					'key' => 'field_5557864d39b01',
					'label' => 'whole or fraction',
					'name' => 'whole_fraction',
					'type' => 'select',
					'instructions' => 'Is the quantity a whole or a fraction?
Example: 1/2 cup is a fraction, 1 tablespoon is a while. This only refers to the number.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'whole' => 'Whole',
						'fraction' => 'Fraction',
					),
					'default_value' => array (
						'whole' => 'whole',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_555554689c305',
					'label' => 'Quantity',
					'name' => 'quantity_whole',
					'type' => 'number',
					'instructions' => 'Please enter the quantity of the ingredient',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5557864d39b01',
								'operator' => '!=',
								'value' => 'fraction',
							),
						),
					),
					'wrapper' => array (
						'width' => 20,
						'class' => '',
						'id' => '',
					),
					'default_value' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_55578786df56d',
					'label' => 'Quantity',
					'name' => 'quantity_fraction',
					'type' => 'select',
					'instructions' => 'Please select the quantity of the ingredient',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5557864d39b01',
								'operator' => '==',
								'value' => 'fraction',
							),
						),
					),
					'wrapper' => array (
						'width' => 20,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'1/2' => '1/2',
						'1/3' => '1/3',
						'2/3' => '2/3',
						'1/4' => '1/4',
						'3/4' => '3/4',
					),
					'default_value' => array (
						'half' => 'half',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_5557897305b35',
					'label' => 'Unit',
					'name' => 'unit',
					'type' => 'select',
					'instructions' => 'Select the unit for this quantity',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 10,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'teaspoon' => 'teaspoon',
						'tablespoon' => 'tablespoon',
						'cup' => 'cup',
                        'us-gal' => 'gallon (US)',
                        'us-quart' => 'quart (US)',
                        'us-pint' => 'pint (US)',
                        'us-oz' => 'ounce (US)',
                        'imp-gal' => 'gallon (Imperial/UK)',
                        'imp-quart' => 'quart (Imperial/UK)',
                        'imp-pint' => 'pint (Imperial/UK)',
                        'imp-oz' => 'ounce (Imperial/UK)',
						'ml' => 'ml',
						'lt' => 'lt',
						'pound' => 'pound',
						'ounce' => 'ounce',
						'gr' => 'gram',
						'kg' => 'kg',
						'mm' => 'mm',
						'cm' => 'cm',
						'm' => 'm',
						'inch' => 'inch',
					),
					'default_value' => array (
						'kg' => 'kg',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_555554af9c306',
					'label' => 'Ingredient',
					'name' => 'ingredient',
					'type' => 'taxonomy',
					'instructions' => 'Please enter the ingredient',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'ingredient',
					'field_type' => 'select',
					'allow_null' => 0,
					'add_term' => 1,
					'load_save_terms' => 1,
					'return_format' => 'id',
					'multiple' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'recipe',
			),
		),
	),
	'menu_order' => 20,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_55555ce88f23e',
	'title' => 'Videos',
	'fields' => array (
		array (
			'key' => 'field_55555ced24348',
			'label' => 'Videos',
			'name' => 'videos',
			'type' => 'repeater',
			'instructions' => 'Have videos? Awesome! Just add them below.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add Video',
			'sub_fields' => array (
				array (
					'key' => 'field_55555d2c24349',
					'label' => 'Video',
					'name' => 'video',
					'type' => 'oembed',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'width' => '',
					'height' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'recipe',
			),
		),
	),
	'menu_order' => 20,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_55555558956b1',
	'title' => 'Recipe Photos',
	'fields' => array (
		array (
			'key' => 'field_5555555f69227',
			'label' => 'Gallery',
			'name' => 'gallery',
			'type' => 'gallery',
			'instructions' => 'Please add photos to accompany this recipe',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'preview_size' => 'thumbnail',
			'library' => 'uploadedTo',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'recipe',
			),
		),
	),
	'menu_order' => 40,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;
